# Copyright 2022-2025 Hewlett Packard Enterprise Development LP
apiVersion: v2
name: cray-dns-unbound
version: 0.9.0

sources:
  - https://github.com/NLnetLabs/unbound
  - https://gitlab.com/klutchell/unbound
description: Kubernetes resources for Cray DNS resolver using Unbound
home: https://github.com/Cray-HPE/cray-dns-unbound
maintainers:
  - name: spillerc-hpe
appVersion: 0.9.0
annotations:
  artifacthub.io/images: |
    - name: cray-dns-unbound
      image: artifactory.algol60.net/csm-docker/stable/cray-dns-unbound:0.9.0
  artifacthub.io/license: MIT
