# Copyright 2022 Hewlett Packard Enterprise Development LP
apiVersion: v2
name: cray-dns-unbound
version: 0.8.1

sources:
  - https://github.com/NLnetLabs/unbound
  - https://gitlab.com/klutchell/unbound
description: Kubernetes resources for Cray DNS resolver using Unbound
home: https://github.com/Cray-HPE/cray-dns-unbound
dependencies:
  - name: cray-service
    version: "~10.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
  - name: dle-hpe
appVersion: 0.8.1
annotations:
  artifacthub.io/images: |
    - name: cray-dns-unbound
      image: artifactory.algol60.net/csm-docker/stable/cray-dns-unbound:0.8.1
  artifacthub.io/license: MIT
