apiVersion: v1
description: "Kubernetes resources for Cray DNS resolver using Unbound"
home: cloud/cray-dns-unbound
name: cray-dns-unbound
version: 0.0.12
sources:
- https://github.com/NLnetLabs/unbound
- https://gitlab.com/klutchell/unbound
