domain_name: example  # removed before packaging

# if changing LoadBalancer IPs, update cray-dhcp-kea
hmnLoadBalancerIp: 10.94.100.225
nmnLoadBalancerIp: 10.92.100.225
nmnLoadBalancerIpLocal_1: 10.92.100.224
nmnLoadBalancerIpLocal_2: 10.92.100.223

powerDNSServerIp: 10.92.100.85

corednsConcurrentConnectionsToFwder: 10000

# remember to match cache and threads this with .cray-service.containers.cray-dns-unbound.resources.requests.cpu in multiples of 2
cache: "2"
threads: "2"

keaApiEndpoint: http://cray-dhcp-kea-api:8000
smdApiEndpoint: http://cray-smd
slsApiEndpoint: http://cray-sls
logLevel: INFO

# Control which HSN NIC is used for the primary nid alias.
# Setting this to all will cause all HSN IPs to be used.
hsnNicAlias: 0

# Controls which IP address ranges unbound will allow queries from.
# If you want to use unbound as an upstream for kube-dns, or allow other pods
# to query the resolver directly, you'll at least need to allow the
# clusterIpV4Cidr range.
#
#
# Following are Shasta subnets beginning v1.3
# HMN          - 10.254.0.0/17
# NMN          - 10.252.0.0/17
# CABINETS HMN - 10.104/16
# CABINETS NMN - 10.100/16 (not a typo)
# METALLB HMN  - 10.94.100/24
# METALLB NMN  - 10.92.100/24
allowedIpRanges:
  - "10.0.0.0/8"
  - "127.0.0.0/8"

# You can set as many forward zones as needed by specifying the zone name
# and forward hosts. Forward hosts can be set by hostname or ip.

forwardZones: []
  # This will be central dns
  # - name: "."
  #   forwardIps:
  #     - 172.30.84.40
  # - name: "craycray.info"
  #   forwardIps:
  #     - "10.1.92.70"

stubZones:
  - name: 10.in-addr.arpa.
    stubIps:
      - "10.92.100.85"

# Local resolution for Shasta zones was moved to the template (CASMNET-719)
# Additional local zones can be defined here.

localZones:
  # - name: "can."
  #   localType: static
  - name: "10.in-addr.arpa."
    localType: nodefault

# Unbound can store DNS records in a "local zone." This facility can be used to
# assign context-specific names to a given IP address, and could also be used for
# private DNS if you don't want or have an external resolver.

localRecords: []
# localRecords:
# - name: "fake3.host.net"
#   ip: "10.12.10.10"

# NOTE:  The commented records.json.gz below is a base64 encoded gzip file that
#        unpacks to an empty list of [] and can be used to reset the configmap.
# binaryData:
#   records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
host_records_gzip: "H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA"


coreDNS:
  forwardToUnbound: true
  namespace: kube-system
  configMapName: coredns
  deploymentName: coredns

infra_cache_numhosts: "1000000"
verbosity: 0
statsInterval: 0
statsCumulative: "no"
serverPort: 5053
exporterPort: 9167
containerConfigDirectory: /etc/unbound

mgrJob:
  schedule:
    minute: "*/2"
    hour: "*"
    day_of_month: "*"
    month: "*"
    day_of_week: "*"

dnsUnboundExporter:
  enabled: true
  service:
    namespace: services
    port: 9167
    targetPort: 9167
    selector:
      app.kubernetes.io/name: cray-dns-unbound
  serviceMonitor:
    namespace: sysmgmt-health
    matchNamespace:
      - services
    interval: 59s
    scrapeTimeout: 50s
    scheme: http
    port: exporter
    metricsRelabelings: {}
    relabelings: {}

cray-service:
  priorityClassName: "csm-high-priority-service"
  type: deployment
  nameOverride: cray-dns-unbound
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "5053"
  replicaCount: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - cray-dns-unbound
            topologyKey: "kubernetes.io/hostname"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  containers:
    cray-dns-unbound:
      name: cray-dns-unbound
      securityContext:
        runAsUser: 101
        runAsGroup: 102
        runAsNonRoot: true
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-dns-unbound
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: 8Gi
      env:
        - name: UNBOUND_CONFIG_DIRECTORY
          value: "/etc/unbound"
        - name: UNBOUND_CONFIGMAP_DIRECTORY
          value: "/configmap"
        - name: UNBOUND_CREATE_PTR_RECORDS
          value: "true"
        - name: DNS_INITIALIZE_INTERVAL_SECONDS
          value: "90"
        - name: UNBOUND_CONTROL_INTERFACE
          value: "127.0.0.1"
      ports:
        - name: udp
          containerPort: 5053
          protocol: UDP
        - name: tcp
          containerPort: 5053
          protocol: TCP
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "kill `cat /etc/unbound/unbound.pid`; sleep 10"]
      volumeMounts:
        - name: cray-dns-unbound-data
          mountPath: "/configmap"
        - name: cray-dns-unbound-jobs
          mountPath: "/srv/unbound"
      livenessProbe:
        exec:
          command:
            - "nslookup"
            - "health.check.unbound"
            - "127.0.0.1:5053"
        initialDelaySeconds: 30
        timeoutSeconds: 2
      readinessProbe:
        exec:
          command:
            - "nslookup"
            - "packages.local"
            # will need to restore for pdns cutover
            # - "health.check.unbound"
            - "127.0.0.1:5053"
        failureThreshold: 1
        initialDelaySeconds: 30
        periodSeconds: 1
        successThreshold: 10
        timeoutSeconds: 1
      nodeSelector: {}
      affinity: {}
      tolerations: []
    unbound-exporter:
      name: unbound-exporter
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        runAsNonRoot: true
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-dns-unbound
        pullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - /usr/bin/unbound_exporter
        - -unbound.host
        - tcp://${UNBOUND_CONTROL_INTERFACE}:${UNBOUND_CONTROL_PORT}
      resources:
        requests:
          cpu: "0.25"
          memory: "256Mi"
        limits:
          cpu: "0.5"
          memory: "512Mi"
      env:
        - name: UNBOUND_CONTROL_INTERFACE
          value: "127.0.0.1"
        - name: UNBOUND_CONTROL_PORT
          value: "8953"
      ports:
        - name: exporter
          containerPort: 9167
          protocol: TCP
      livenessProbe:
        httpGet:
          port: 9167
          path: /metrics
        initialDelaySeconds: 30
        timeoutSeconds: 2
      readinessProbe:
        httpGet:
          port: 9167
          path: /metrics
        failureThreshold: 1
        initialDelaySeconds: 30
        periodSeconds: 1
        successThreshold: 10
        timeoutSeconds: 1
      nodeSelector: {}
      affinity: {}
      tolerations: []
  volumes:
    - name: cray-dns-unbound-data
      configMap:
        name: cray-dns-unbound
    - name: cray-dns-unbound-jobs
      configMap:
        defaultMode: 0777
        name: cray-dns-unbound-jobs
global:
  chart:
    name: cray-dns-unbound
    version: 0.7.27
  appVersion: 0.7.27
