apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
# NOTE:  The commented records.json.gz below is a base64 encoded gzip file that
#        unpacks to an empty list of [] and can be used to reset the configmap.
# binaryData:
#   records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
binaryData:
  records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
data:
  unbound.conf: |-
    server:
        module-config: "iterator"
        chroot: ""
        interface: 127.0.0.1
        interface: 0.0.0.0
        port: {{ .Values.serverPort }}
        so-reuseport: yes
        do-ip6: no
        do-daemonize: no
        use-syslog: no
        logfile: ""
        access-control: 127.0.0.1/32 allow
        num-threads: {{ .Values.numThreads }}
        verbosity: {{ .Values.verbosity }}
        log-queries: no
        statistics-interval: {{ .Values.statsInterval }}
        statistics-cumulative: {{ .Values.statsCumulative }}
        # Minimum lifetime of cache entries in seconds
        cache-min-ttl: 300
        # Maximum lifetime of cached entries
        cache-max-ttl: 14400
        prefetch: yes
        prefetch-key: yes
        # Optimisations
        msg-cache-slabs: 8
        rrset-cache-slabs: 8
        infra-cache-slabs: 8
        key-cache-slabs: 8
        # increase memory size of the cache
        rrset-cache-size: 1024m
        msg-cache-size: 512m
        # increase buffer size so that no messages are lost in traffic spikes
        so-rcvbuf: 5m

        local-data: "health.check.unbound A 127.0.0.1"
        local-data-ptr: "127.0.0.1 health.check.unbound"
        include: {{ .Values.containerConfigDirectory }}/records.conf

        {{- range .Values.allowedIpRanges }}
        access-control: {{ . }} allow
        {{- end }}

        {{- range .Values.localRecords }}
        local-data: "{{ .name }} A {{ .ip }}"
        local-data-ptr: "{{ .ip }} {{ .name }}"
        {{- end }}

        local-zone: "local" static
        local-zone: "nmn." static
        local-zone: "hmn." static
    {{- range .Values.localZones }}
        local-zone: "{{ .name }}" {{ .localType }}
    {{- end }}


    {{- if .Values.forwardZones }}
    {{- range .Values.forwardZones }}

    forward-zone:
        name: {{ .name }}
        {{- range .forwardHosts }}
        forward-host: {{ . }}
        {{- end }}
        {{- range .forwardIps }}
        forward-addr: {{ . }}
        {{- end }}
    {{- end }}
    {{- else }}
        local-zone: "." static
    {{- end }}

    stub-zone:
        name: {{ required "domain_name is missing from cray-dns-unbound customizations.yaml values" .Values.domain_name }}
        stub-addr: 10.92.100.85

    {{- range .Values.stubZones }}

    stub-zone:
        name: {{ .name }}
        {{- range .stubHosts }}
        stub-host: {{ . }}
        {{- end }}
        {{- range .stubIps }}
        stub-addr: {{ . }}
        {{- end }}
    {{- end }}
