apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
# NOTE:  The commented records.json.gz below is a base64 encoded gzip file that
#        unpacks to an empty list of [] and can be used to reset the configmap.
# binaryData:
#   records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
binaryData:
  {{- $configmap := (lookup "v1" "ConfigMap" .Release.Namespace "cray-dns-unbound") }}
  {{- if $configmap }}
  {{- $records := get $configmap.binaryData "records.json.gz" }}
  records.json.gz: {{ $records }}
  {{- else }}
  records.json.gz: {{ .Values.host_records_gzip }}
  {{- end }}
data:
  {{- if $configmap }}
  {{- $records := get $configmap.data "custom_records.conf" }}
  {{- if $records }}
  custom_records.conf: |-
  {{- $records | nindent 4 }}
  {{- else }}
  custom_records.conf: |-
    # Add any additional local-data or local-data-ptr records here, one per line.
    # See https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-local-data for syntax.
    # WARNING: Syntax errors here will cause Unbound to fail to start and the cluster DNS service will fail.
    #
    # Examples:
    # local-data: "axfr-service.example.com A 10.252.4.254"
    # local-data-ptr: "10.252.4.254 axfr-service.example.com"
    # local-data: "_axfr-service._tcp.example.com 3600 IN SRV 0 100 8080 axfr-service.example.com."
  {{- end }}
  {{- end }}
  unbound.conf: |-
    server:
        module-config: "iterator"
        chroot: ""
        interface: 127.0.0.1
        interface: 0.0.0.0
        port: {{ .Values.serverPort }}
        so-reuseport: yes
        do-ip6: no
        do-daemonize: no
        use-syslog: no
        logfile: ""
        access-control: 127.0.0.1/32 allow
        num-threads: {{ .Values.threads }}
        verbosity: {{ .Values.verbosity }}
        log-queries: no
        statistics-interval: {{ .Values.statsInterval }}
        statistics-cumulative: {{ .Values.statsCumulative }}
        # Minimum lifetime of cache entries in seconds
        cache-min-ttl: 180
        # Maximum lifetime of cached entries
        cache-max-ttl: 3600
        # Maximum lifetime of negative responses
        cache-max-negative-ttl: 5
        prefetch: yes
        prefetch-key: yes
        # Optimisations
        msg-cache-slabs: {{ .Values.cache }}
        rrset-cache-slabs: {{ .Values.cache }}
        infra-cache-slabs: {{ .Values.cache }}
        key-cache-slabs: {{ .Values.cache }}
        # increase memory size of the cache
        rrset-cache-size: 1024m
        msg-cache-size: 512m
        infra-cache-numhosts: {{ .Values.infra_cache_numhosts }}
        # increase buffer size so that no messages are lost in traffic spikes
        so-rcvbuf: 5m
        # Set this to no for compatibility with PBSPro which requires deterministic ordering of rrsets.
        rrset-roundrobin: no
        # Continue to health check down DNS servers so they aren't offline longer than necessary
        infra-keep-probing: yes
        infra-host-ttl: 30

        local-data: "health.check.unbound A 127.0.0.1"
        local-data-ptr: "127.0.0.1 health.check.unbound"
        include: {{ .Values.containerConfigDirectory }}/records.conf
        include: {{ .Values.containerConfigDirectory }}/custom_records.conf

        {{- range .Values.allowedIpRanges }}
        access-control: {{ . }} allow
        {{- end }}

        {{- range .Values.localRecords }}
        local-data: "{{ .name }} A {{ .ip }}"
        local-data-ptr: "{{ .ip }} {{ .name }}"
        {{- end }}

        local-zone: "local" static
        local-zone: "nmn." static
        local-zone: "hmn." static
        local-zone: "mtl." static
        local-zone: "hsn." static
        local-zone: "can." static
        local-zone: "cmn." static
        local-zone: "chn." static
    {{- range .Values.localZones }}
        local-zone: "{{ .name }}" {{ .localType }}
    {{- end }}

    {{- if .Values.forwardZones }}
    {{- range .Values.forwardZones }}

    forward-zone:
        name: {{ .name }}
        {{- range .forwardHosts }}
        forward-host: {{ . }}
        {{- end }}
        {{- range .forwardIps }}
        forward-addr: {{ . }}
        {{- end }}
        forward-first: yes
    {{- end }}
    {{- end }}

    stub-zone:
        name: {{ required "domain_name is missing from cray-dns-unbound customizations.yaml values" .Values.domain_name }}
        stub-addr: {{ .Values.powerDNSServerIp }}

    {{- range .Values.stubZones }}

    stub-zone:
        name: {{ .name }}
        {{- range .stubHosts }}
        stub-host: {{ . }}
        {{- end }}
        {{- range .stubIps }}
        stub-addr: {{ . }}
        {{- end }}
    {{- end }}

     remote-control:
        control-enable: yes
        control-use-cert: no
        control-interface: 0.0.0.0
