apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
# NOTE:  The commented records.json.gz below is a base64 encoded gzip file that
#        unpacks to an empty list of [] and can be used to reset the configmap.
# binaryData:
#   records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
binaryData:
  records.json.gz: H4sICLQ/Z2AAA3JlY29yZHMuanNvbgCLjuUCAETSaHADAAAA
data:
  unbound.conf: |-
    server:
        module-config: "iterator"
        chroot: ""
        interface: 127.0.0.1
        interface: 0.0.0.0
        port: {{ .Values.serverPort }}
        so-reuseport: yes
        do-ip6: no
        do-daemonize: no
        use-syslog: no
        logfile: ""
        access-control: 127.0.0.1/32 allow
        num-threads: {{ .Values.numThreads }}
        verbosity: {{ .Values.verbosity }}
        statistics-interval: {{ .Values.statsInterval }}
        statistics-cumulative: {{ .Values.statsCumulative }}

        local-data: "health.check.unbound A 127.0.0.1"
        local-data-ptr: "127.0.0.1 health.check.unbound"
        include: {{ .Values.containerConfigDirectory }}/records.conf

        {{- range .Values.allowedIpRanges }}
        access-control: {{ . }} allow
        {{- end }}

        {{- range .Values.localRecords }}
        local-data: "{{ .name }} A {{ .ip }}"
        local-data-ptr: "{{ .ip }} {{ .name }}"
        {{- end }}

    {{- range .Values.localZones }}
        local-zone: "{{ .name }}" {{ .localType }}
    {{- end }}

    {{- range .Values.forwardZones }}

    forward-zone:
        name: {{ .name }}
        {{- range .forwardHosts }}
        forward-host: {{ . }}
        {{- end }}
        {{- range .forwardIps }}
        forward-addr: {{ . }}
        {{- end }}
    {{- end }}

    {{- range .Values.stubZones }}

    stub-zone:
        name: {{ .name }}
        {{- range .stubHosts }}
        stub-host: {{ . }}
        {{- end }}
        {{- range .stubIps }}
        stub-addr: {{ . }}
        {{- end }}
    {{- end }}
