apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
data:
  unbound.conf: |-
    server:
        chroot: ""
        num-threads: {{ .Values.numThreads }}
        directory: "{{ .Values.containerConfigDirectory }}"
        port: {{ .Values.serverPort }}
        so-reuseport: yes
        do-daemonize: yes
        logfile: ""
        use-syslog: no
        verbosity: {{ .Values.verbosity }}
        statistics-interval: {{ .Values.statsInterval }}
        statistics-cumulative: {{ .Values.statsCumulative }}

        module-config: "iterator"

        interface: 127.0.0.1@{{ .Values.serverPort }}
        interface: 0.0.0.0@{{ .Values.serverPort }}

        #do-ip6: no
        #domain-insecure: *
        #private-domain: "craycray.info"

        access-control: 127.0.0.1/32 allow

        {{- range .Values.allowedIpRanges }}
        access-control: {{ . }} allow
        {{- end }}

        {{- range .Values.localRecords }}
        local-data: "{{ .name }} A {{ .ip }}"
        local-data-ptr: "{{ .ip }} {{ .name }}"
        {{- end }}

        local-data: "health.check.unbound A 127.0.0.1"
        local-data-ptr: "127.0.0.1 health.check.unbound"
        include: {{ .Values.containerConfigDirectory }}/a-records.conf

    {{- range .Values.localZones }}
        local-zone: "{{ .name }}" {{ .localType }}
    {{- end }}

    {{- range .Values.forwardZones }}

    forward-zone:
        name: {{ .name }}
        {{- range .forwardHosts }}
        forward-host: {{ . }}
        {{- end }}
        {{- range .forwardIps }}
        forward-addr: {{ . }}
        {{- end }}
    {{- end }}

    {{- range .Values.stubZones }}

    stub-zone:
        name: {{ .name }}
        {{- range .stubHosts }}
        stub-host: {{ . }}
        {{- end }}
        {{- range .stubIps }}
        stub-addr: {{ . }}
        {{- end }}
    {{- end }}
