apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cray-dns-unbound.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cray-dns-unbound.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        traffic.sidecar.istio.io/excludeOutboundPorts: "5053"
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      priorityClassName: csm-high-priority-service
      containers:
      - name: unbound
        image: {{ include "cray-dns-unbound.image-prefix" .Values }}{{ .Values.image.repository }}:{{ .Values.image.tag | default (include "cray-dns-unbound.app-version" .) }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        env:
        - name: UNBOUND_CONFIG_DIRECTORY
          value: "{{ .Values.containerConfigDirectory }}"
        - name: UNBOUND_CONFIGMAP_DIRECTORY
          value: "{{ .Values.containerConfigMapDataDirectory }}"
        - name: UNBOUND_CREATE_PTR_RECORDS
          value: "{{ .Values.createPtrRecords }}"
        - name: DNS_INITIALIZE_INTERVAL_SECONDS
          value: "{{ .Values.dnsInitializeIntervalSeconds }}"
        ports:
        - name: udp
          containerPort: {{ .Values.serverPort }}
          protocol: UDP
        - name: tcp
          containerPort: {{ .Values.serverPort }}
          protocol: TCP
        - name: exporter
          containerPort: {{ .Values.exporterPort }}
          protocol: TCP
        volumeMounts:
        - name: unbound
          mountPath: "{{ .Values.containerConfigDirectory }}/unbound.conf"
          subPath: unbound.conf
        - name: unbound
          mountPath: "{{ .Values.containerConfigDirectory }}/records.json.gz"
          subPath: records.json.gz
        - name: configmap-data
          mountPath: "{{ .Values.containerConfigMapDataDirectory }}"
        livenessProbe:
          exec:
            command:
            - "nslookup"
            - "health.check.unbound"
            - "127.0.0.1:{{ .Values.serverPort }}"
          initialDelaySeconds: 30
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - "nslookup"
            - "packages.local"
            # will need to restore for pdns cutover
            #- "health.check.unbound"
            - "127.0.0.1:{{ .Values.serverPort }}"
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 3
          timeoutSeconds: 1
      volumes:
      - name: unbound
        configMap:
          name: {{ template "cray-dns-unbound.fullname" . }}
          items:
          - key: unbound.conf
            path: unbound.conf
          - key: records.json.gz
            path: records.json.gz
      - name: configmap-data
        configMap:
          name: cray-dns-unbound
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
