apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cray-dns-unbound.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
