---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-manager
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
  annotations:
    release/revision: "{{ .Release.Revision }}"
spec:
  {{ with .Values.mgrJob.schedule -}}
  schedule: "{{.minute}} {{.hour}} {{.day_of_month}} {{.month}} {{.day_of_week}}"
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cronjob-name: {{ template "cray-dns-unbound.fullname" . }}-manager
        spec:
          restartPolicy: Never
          serviceAccountName: {{ template "cray-dns-unbound.fullname" . }}-manager
          terminationGracePeriodSeconds: 1200
          activeDeadlineSeconds: 1200
          containers:
          - name: manager
            image: {{ include "cray-dns-unbound.image-prefix" .Values }}{{ .Values.image.repository }}:{{ .Values.image.tag | default (include "cray-dns-unbound.app-version" .) }}
            command: ["/srv/unbound/manager.py"]
            env:
            - name: KEA_API_ENDPOINT
              value: "{{ .Values.keaApiEndpoint }}"
            - name: KUBERNETES_UNBOUND_CONFIGMAP_NAME
              value: "{{ template "cray-dns-unbound.fullname" . }}"
            - name: KUBERNETES_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: KUBERNETES_UNBOUND_DEPLOYMENT_NAME
              value: "{{ template "cray-dns-unbound.fullname" . }}"
            resources:
              limits:
                cpu: "8"
                memory: "8Gi"
              requests:
                cpu: "4"
                memory: "4Gi"