---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-manager
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
  annotations:
    release/revision: "{{ .Release.Revision }}"
spec:
  {{ with .Values.mgrJob.schedule -}}
  schedule: "{{.minute}} {{.hour}} {{.day_of_month}} {{.month}} {{.day_of_week}}"
  {{- end }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cronjob-name: {{ template "cray-dns-unbound.fullname" . }}-manager
        spec:
          restartPolicy: Never
          serviceAccountName: {{ template "cray-dns-unbound.fullname" . }}-manager
          terminationGracePeriodSeconds: 1200
          activeDeadlineSeconds: 1200
          containers:
          - name: manager
            image: {{ index .Values "cray-service" "containers" "cray-dns-unbound" "image" "repository" }}:{{ default .Chart.AppVersion (index .Values "cray-service" "containers" "cray-dns-unbound" "image" "tag") }}
            imagePullPolicy: {{ index .Values "cray-service" "containers" "cray-dns-unbound" "image" "pullPolicy" }}
            command: ["/srv/unbound/manager.py"]
            env:
            - name: HSN_NIC_ALIAS
              value: "{{ .Values.hsnNicAlias }}"
            - name: KEA_API_ENDPOINT
              value: "{{ .Values.keaApiEndpoint }}"
            - name: SMD_API_ENDPOINT
              value: "{{ .Values.smdApiEndpoint }}"
            - name: SLS_API_ENDPOINT
              value: "{{ .Values.slsApiEndpoint }}"
            - name: KUBERNETES_UNBOUND_CONFIGMAP_NAME
              value: "{{ template "cray-dns-unbound.fullname" . }}"
            - name: KUBERNETES_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: KUBERNETES_UNBOUND_DEPLOYMENT_NAME
              value: "{{ template "cray-dns-unbound.fullname" . }}"
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            resources:
              limits:
                cpu: "8"
                memory: "8Gi"
              requests:
                cpu: "500m"
                memory: "1Gi"
            volumeMounts:
            - mountPath: /srv/unbound
              name: cray-dns-unbound-jobs
          volumes:
          - configMap:
              defaultMode: 0777
              name: cray-dns-unbound-jobs
            name: cray-dns-unbound-jobs
