---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-manager
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-manager-role-binding
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "cray-dns-unbound.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}

{{ if .Values.coreDNS.forwardToUnbound -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-coredns
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-coredns-role
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  resourceNames: ["{{ .Values.coreDNS.deploymentName }}"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ .Values.coreDNS.configMapName }}"]
  verbs: ["get", "patch"]
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted-transition-net-raw
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cray-dns-unbound.fullname" . }}-coredns-role-binding
  namespace: {{ .Values.coreDNS.namespace }}
  labels:
    {{- include "cray-dns-unbound.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "cray-dns-unbound.fullname" . }}-coredns
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cray-dns-unbound.fullname" . }}-coredns-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cray-unbound-coredns-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-transition-net-raw-psp
subjects:
  - kind: ServiceAccount
    name: cray-dns-unbound-manager
    namespace: services
  - kind: ServiceAccount
    name: cray-dns-unbound-coredns
    namespace: services
{{- end }}