---
apiVersion: v1
kind: Service
metadata:
  name: cray-dns-unbound-tcp-hmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/allow-shared-ip:  cray-dns-unbound-hmn
    external-dns.alpha.kubernetes.io/hostname: cray-dns-unbound
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.hmnLoadBalancerIp }}
  ports:
    - name: unbound-server-tcp-hmn
      port: 53
      protocol: TCP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dns-unbound
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dns-unbound-tcp-nmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip:  cray-dns-unbound-nmn
    external-dns.alpha.kubernetes.io/hostname: cray-dns-unbound
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.nmnLoadBalancerIp }}
  ports:
    - name: unbound-server-tcp-nmn
      port: 53
      protocol: TCP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dns-unbound
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dns-unbound-udp-hmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: hardware-management
    metallb.universe.tf/allow-shared-ip:  cray-dns-unbound-hmn
    external-dns.alpha.kubernetes.io/hostname: cray-dns-unbound
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.hmnLoadBalancerIp }}
  ports:
    - name: unbound-server-udp-hmn
      port: 53
      protocol: UDP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dns-unbound
---
apiVersion: v1
kind: Service
metadata:
  name: cray-dns-unbound-udp-nmn
  labels:
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip:  cray-dns-unbound-nmn
    external-dns.alpha.kubernetes.io/hostname: cray-dns-unbound
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.nmnLoadBalancerIp }}
  ports:
    - name: unbound-server-udp-nmn
      port: 53
      protocol: UDP
      targetPort: {{ .Values.serverPort }}
  selector:
    app.kubernetes.io/name: cray-dns-unbound