name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: '20 20 * * *'
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      lint-pre-script: |
        echo "domain_name: example.com" >> kubernetes/cray-dns-unbound/values.yaml
      test-charts: false
      scan-chart-snyk-args: "--severity-threshold=high --policy-path=kubernetes/.snyk"
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
